volumes:
  splunk-etc:

services:

  splunk:
    container_name: splunk
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "password"
    volumes:
      - splunk-etc:/opt/splunk/etc
      - /var/log:/opt/splunk/var/log
      - ./conf/inputs.conf:/opt/splunk/etc/system/local/inputs.conf
    ports:
      - "8000:8000"
      - "9997:9997"
